#ifndef MQ1_SINGLE_HEADER_BYTES
#define MQ1_SINGLE_HEADER_BYTES 384
#endif

#ifndef MQ1_SINGLE_HEADER_NUM_FIELDS
#define MQ1_SINGLE_HEADER_NUM_FIELDS 54
#endif

#ifndef MQ1_QUAD_HEADER_BYTES
#define MQ1_QUAD_HEADER_BYTES 768
#endif

#ifndef MQ1_QUAD_HEADER_NUM_FIELDS
#define MQ1_QUAD_HEADER_NUM_FIELDS 138
#endif

#ifndef MQ1_CHAR_LEN_HEADER_ID
#define MQ1_CHAR_LEN_HEADER_ID 4
#endif

#ifndef MQ1_CHAR_LEN_PIXEL_DEPTH
#define MQ1_CHAR_LEN_PIXEL_DEPTH 4
#endif

#ifndef MQ1_CHAR_LEN_SENSOR_LAYOUT
#define MQ1_CHAR_LEN_SENSOR_LAYOUT 7
#endif

#ifndef MQ1_CHAR_LEN_CHIP_SELECT
#define MQ1_CHAR_LEN_CHIP_SELECT 3
#endif

#ifndef MQ1_CHAR_LEN_TIMESTAMP
#define MQ1_CHAR_LEN_TIMESTAMP 27
#endif

#ifndef MQ1_FLOAT_LEN_THRESHOLD
#define MQ1_FLOAT_LEN_THRESHOLD 8
#endif

#ifndef MQ1_CHAR_LEN_HEADER_EXTENSION_ID
#define MQ1_CHAR_LEN_HEADER_EXTENSION_ID 5
#endif

#ifndef MQ1_CHAR_LEN_EXTENDED_TIMESTAMP
#define MQ1_CHAR_LEN_EXTENDED_TIMESTAMP 31
#endif
